package com.example.techstorm223

sealed class NavigationItem(var route: String, var icon: Int, var title: String)
{
    object Home : NavigationItem("home", R.drawable.ic_home, "Home")
    object Schedule : NavigationItem("schedule", R.drawable.ic_schedule, "Schedule")
    object Results : NavigationItem("results", R.drawable.ic_results, "Results")
    object Team : NavigationItem("team", R.drawable.ic_team, "Team")
    object Sponcers : NavigationItem("sponcers", R.drawable.ic_sponcers, "Sponcers")
    object Aboutus : NavigationItem("aboutus", R.drawable.ic_aboutus, "About Us")

    object Share : NavigationItem("share", R.drawable.ic_share, "Share")
    object Contact : NavigationItem("contact", R.drawable.ic_contact, "Contact")
    object Developers : NavigationItem("developers", R.drawable.ic_dev, "Developers")
    object Rovers_List : NavigationItem("Rovers List", R.drawable.ic_new, "Rovers_List")
    object Rovers_List2 : NavigationItem("Rovers List2", R.drawable.ic_new, "Rovers_List2")
    object BrainTeasersList : NavigationItem("brainTeasersList List2", R.drawable.ic_new, "BrainTeasersList")
    object Appmania : NavigationItem("appmania", R.drawable.ic_new, "Appmania")
    object Fantac : NavigationItem("fantac", R.drawable.ic_new, "Fantac")
    object Omegatrix : NavigationItem("omegatrix", R.drawable.ic_new, "Omegatrix")
    object Technomania : NavigationItem("echnomania", R.drawable.ic_new, "Technomania")
    object RoCombat : NavigationItem("roCombat", R.drawable.ic_new, "RoCombat")
    object RoNavigator : NavigationItem("roNavigator", R.drawable.ic_new, "RoNavigator")
    object RoPicker : NavigationItem("roPicker", R.drawable.ic_new, "RoPicker")
    object RoSoccer : NavigationItem("roSoccer", R.drawable.ic_new, "RoSoccer")
    object RoTerrance : NavigationItem("roTerrance", R.drawable.ic_new, "RoTerrance")
    object RoWings : NavigationItem("roWings", R.drawable.ic_new, "RoWings")
    object RoCarrom : NavigationItem("gamesList", R.drawable.ic_new, "GamesList")
    object GamesList : NavigationItem("needForSpeed", R.drawable.ic_new, "NeedForSpeed")
    object NeedForSpeed : NavigationItem("roCarrom", R.drawable.ic_new, "RoCarrom")
    object Coc : NavigationItem("coc", R.drawable.ic_new, "Coc")
    object Fifa : NavigationItem("fifa", R.drawable.ic_new, "Fifa")
    object Knet : NavigationItem("knet", R.drawable.ic_new, "Knet")
    object Exposcience : NavigationItem("exposcience", R.drawable.ic_new, "Exposcience")
    object CreativeList : NavigationItem("creativeList", R.drawable.ic_new, "CreativeList")
    object PassionWithReels : NavigationItem("passionWithReels", R.drawable.ic_new, "PassionWithReels")
    object MmLive : NavigationItem("mmLive", R.drawable.ic_new, "MmLive")
    object IdeaPresentation : NavigationItem("ideaPresentation", R.drawable.ic_new, "IdeaPresentation")
    object Gallery : NavigationItem("gallery", R.drawable.ic_gallery, "Gallery")
    object PhotoGallery : NavigationItem("photoGallery", R.drawable.ic_gallery, "PhotoGallery")

}